apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tortuga-hoi
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tortuga-hoi.nais.preprod.local
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 12
    max: 12
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
  prometheus:
    enabled: true